export const image = [
    '../img/Icon1.png',
    '../img/Icon2.png',
    '../img/Vector.png',
    '../img/image 25.png',
    '../img/lupa.png',
    '../img/blackLupa.png',
    '../img/kisspng-cafe-chocolate-covered-coffee-bean-espresso-5aeee25cddd876 1.png',
    '../img/kisspng-coffee-espresso-cappuccino-cafe-breakfast-coffee-5abb12d39e9a33 1.png',
    '../img/kisspng-jamaican-blue-mountain-coffee-cafe-chocolate-cover-coffee-stain-5b161a3dc7a4d2 1.png',
    '../img/kisspng-latte-macchiato-espresso-coffee-cappuccino-jura-giga-5-aluminium-kavos-inovai-5bf2913b055f41 1.png',
    '../img/kisspng-teapot-glass-kettle-coffee-glass-teapot-5b2b7b48412cb5 1.png',
    '../img/image 3.png',
    '../img/Vector2.png',
    '../img/kisspng-coffee-bean-cafe-clip-art-messy-coffee-beans-5a8331b6c12808 1.png',
    '../img/Coffeimg.png',
    '../img/CoffeZer.png',
    '../img/Stars.png',
    '../img/PointsOr.png',
    '../img/WhiteVector.png',
    '../img/pngwing 2.png',
    '../img/kisspng-coffee-bean-tea-cafe-coffee-beans-5abbc29114b2e2 1.png',
    '../img/Rectangle 22.png',
    '../img/image 10.png',
    '../img/WhiteDown.png',
    '../img/imageVectorUp.png',
    '../img/Tanzania.png',
    '../img/Iphone1.png',
    '../img/Iphone2.png',
    '../img/Rectangle 23.png',
    '../img/OrangeDown.png',


]